{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 0 seconds","timestamp":"2023-08-23T18:30:06.230Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 6 seconds","timestamp":"2023-08-23T18:30:06.231Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 5 seconds","timestamp":"2023-08-23T18:30:07.006Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 3 seconds","timestamp":"2023-08-23T18:30:11.595Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 4 seconds","timestamp":"2023-08-23T18:30:11.596Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 26 seconds","timestamp":"2023-08-23T18:30:14.830Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 2 seconds","timestamp":"2023-08-23T18:30:16.237Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T18:30:18.667Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 4 seconds","timestamp":"2023-08-23T18:33:06.941Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 12 seconds","timestamp":"2023-08-23T18:33:06.943Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 27 seconds","timestamp":"2023-08-23T18:33:11.118Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 6 seconds","timestamp":"2023-08-23T18:33:12.973Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 0 seconds","timestamp":"2023-08-23T18:33:12.974Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 5 seconds","timestamp":"2023-08-23T18:33:13.197Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 1 seconds","timestamp":"2023-08-23T18:33:18.286Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T18:33:19.351Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 1 seconds","timestamp":"2023-08-23T18:38:19.737Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 11 seconds","timestamp":"2023-08-23T18:38:21.368Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 25 seconds","timestamp":"2023-08-23T18:38:32.994Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 2 seconds","timestamp":"2023-08-23T18:38:44.235Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 11 seconds","timestamp":"2023-08-23T18:38:44.236Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 10 seconds","timestamp":"2023-08-23T18:38:46.406Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 5 seconds","timestamp":"2023-08-23T18:38:50.080Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 7 seconds","timestamp":"2023-08-23T18:38:50.080Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 28 seconds","timestamp":"2023-08-23T18:38:55.877Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 5 seconds","timestamp":"2023-08-23T18:38:57.335Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T18:39:02.561Z"}
{"date":"Wed Aug 23 2023 19:39:42 GMT+0100 (West Africa Standard Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: (0 , postgres_1.initDatabase) is not a function\nTypeError: (0 , postgres_1.initDatabase) is not a function\n    at /Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:11:39\n    at Object.<anonymous> (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:15:3)\n    at Module._compile (node:internal/modules/cjs/loader:1126:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:17:47","os":{"loadavg":[2.21337890625,2.8623046875,3.4658203125],"uptime":1287114},"process":{"argv":["/usr/local/bin/node","/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js"],"cwd":"/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question","execPath":"/usr/local/bin/node","gid":20,"memoryUsage":{"arrayBuffers":368233,"external":3092266,"heapTotal":21774336,"heapUsed":15290576,"rss":51666944},"pid":31404,"uid":501,"version":"v16.17.0"},"stack":"TypeError: (0 , postgres_1.initDatabase) is not a function\n    at /Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:11:39\n    at Object.<anonymous> (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:15:3)\n    at Module._compile (node:internal/modules/cjs/loader:1126:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:17:47","timestamp":"2023-08-23T18:39:42.955Z","trace":[{"column":39,"file":"/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js","function":null,"line":11,"method":null,"native":false},{"column":3,"file":"/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js","function":null,"line":15,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1126,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1180,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1004,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":839,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":17,"method":null,"native":false}]}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 0 seconds","timestamp":"2023-08-23T18:39:42.958Z"}
{"date":"Wed Aug 23 2023 19:39:48 GMT+0100 (West Africa Standard Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: (0 , postgres_1.initDatabase) is not a function\nTypeError: (0 , postgres_1.initDatabase) is not a function\n    at /Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:11:39\n    at Object.<anonymous> (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:15:3)\n    at Module._compile (node:internal/modules/cjs/loader:1126:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:17:47","os":{"loadavg":[2.1962890625,2.84765625,3.45703125],"uptime":1287120},"process":{"argv":["/usr/local/bin/node","/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js"],"cwd":"/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question","execPath":"/usr/local/bin/node","gid":20,"memoryUsage":{"arrayBuffers":373421,"external":3092266,"heapTotal":21774336,"heapUsed":15243688,"rss":49901568},"pid":31419,"uid":501,"version":"v16.17.0"},"stack":"TypeError: (0 , postgres_1.initDatabase) is not a function\n    at /Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:11:39\n    at Object.<anonymous> (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:15:3)\n    at Module._compile (node:internal/modules/cjs/loader:1126:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:17:47","timestamp":"2023-08-23T18:39:48.856Z","trace":[{"column":39,"file":"/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js","function":null,"line":11,"method":null,"native":false},{"column":3,"file":"/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js","function":null,"line":15,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1126,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1180,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1004,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":839,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":81,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":47,"file":"node:internal/main/run_main_module","function":null,"line":17,"method":null,"native":false}]}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 8 seconds","timestamp":"2023-08-23T18:39:48.861Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 1 seconds","timestamp":"2023-08-23T18:39:58.063Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 6 seconds","timestamp":"2023-08-23T18:39:58.064Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 3 seconds","timestamp":"2023-08-23T18:39:59.934Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 25 seconds","timestamp":"2023-08-23T18:40:03.218Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 7 seconds","timestamp":"2023-08-23T18:40:04.105Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 12 seconds","timestamp":"2023-08-23T18:40:04.106Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 24 seconds","timestamp":"2023-08-23T18:40:11.838Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 21 seconds","timestamp":"2023-08-23T18:40:16.374Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T18:40:36.485Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 4 seconds","timestamp":"2023-08-23T18:47:45.224Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 18 seconds","timestamp":"2023-08-23T18:47:45.225Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 20 seconds","timestamp":"2023-08-23T18:47:49.340Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 8 seconds","timestamp":"2023-08-23T18:47:51.349Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 17 seconds","timestamp":"2023-08-23T18:47:51.350Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 0 seconds","timestamp":"2023-08-23T18:47:59.871Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 7 seconds","timestamp":"2023-08-23T18:47:59.997Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T18:48:07.890Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 0 seconds","timestamp":"2023-08-23T18:51:41.010Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 7 seconds","timestamp":"2023-08-23T18:51:41.011Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 2 seconds","timestamp":"2023-08-23T18:51:41.843Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 0 seconds","timestamp":"2023-08-23T18:51:44.448Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T18:51:45.086Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 6 seconds","timestamp":"2023-08-23T18:54:55.565Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 2 seconds","timestamp":"2023-08-23T18:54:55.566Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 28 seconds","timestamp":"2023-08-23T18:54:58.008Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 8 seconds","timestamp":"2023-08-23T18:55:01.536Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 18 seconds","timestamp":"2023-08-23T18:55:01.537Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 0 seconds","timestamp":"2023-08-23T18:55:14.128Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 8 seconds","timestamp":"2023-08-23T18:55:14.132Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 10 seconds","timestamp":"2023-08-23T18:55:14.653Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 5 seconds","timestamp":"2023-08-23T18:55:20.219Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 7 seconds","timestamp":"2023-08-23T18:55:20.220Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 13 seconds","timestamp":"2023-08-23T18:55:25.795Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 23 seconds","timestamp":"2023-08-23T18:55:27.992Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T18:55:39.303Z"}
{"date":"Wed Aug 23 2023 19:55:42 GMT+0100 (West Africa Standard Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Unexpected token ';'\n/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/util/postgres.js:17\n        const connection = await db.;\n                                    ^\n\nSyntaxError: Unexpected token ';'\n    at Object.compileFunction (node:vm:360:18)\n    at wrapSafe (node:internal/modules/cjs/loader:1055:15)\n    at Module._compile (node:internal/modules/cjs/loader:1090:27)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\n    at Module.require (node:internal/modules/cjs/loader:1028:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:5:20)\n    at Module._compile (node:internal/modules/cjs/loader:1126:14)","os":{"loadavg":[3.2255859375,2.951171875,3.1220703125],"uptime":1288074},"process":{"argv":["/usr/local/bin/node","/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js"],"cwd":"/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question","execPath":"/usr/local/bin/node","gid":20,"memoryUsage":{"arrayBuffers":33742,"external":2442332,"heapTotal":19677184,"heapUsed":12641408,"rss":45322240},"pid":33401,"uid":501,"version":"v16.17.0"},"stack":"/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/util/postgres.js:17\n        const connection = await db.;\n                                    ^\n\nSyntaxError: Unexpected token ';'\n    at Object.compileFunction (node:vm:360:18)\n    at wrapSafe (node:internal/modules/cjs/loader:1055:15)\n    at Module._compile (node:internal/modules/cjs/loader:1090:27)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)\n    at Module.load (node:internal/modules/cjs/loader:1004:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:839:12)\n    at Module.require (node:internal/modules/cjs/loader:1028:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.<anonymous> (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js:5:20)\n    at Module._compile (node:internal/modules/cjs/loader:1126:14)","timestamp":"2023-08-23T18:55:42.677Z","trace":[{"column":18,"file":"node:vm","function":"Object.compileFunction","line":360,"method":"compileFunction","native":false},{"column":15,"file":"node:internal/modules/cjs/loader","function":"wrapSafe","line":1055,"method":null,"native":false},{"column":27,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1090,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1180,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1004,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":839,"method":"_load","native":false},{"column":19,"file":"node:internal/modules/cjs/loader","function":"Module.require","line":1028,"method":"require","native":false},{"column":18,"file":"node:internal/modules/cjs/helpers","function":"require","line":102,"method":null,"native":false},{"column":20,"file":"/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/dist/index.js","function":null,"line":5,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1126,"method":"_compile","native":false}]}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: TypeError: connection.done is not a function. Reconnecting in 4 seconds","timestamp":"2023-08-23T18:55:48.767Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: TypeError: connection.done is not a function. Reconnecting in 6 seconds","timestamp":"2023-08-23T18:55:48.768Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 7 seconds","timestamp":"2023-08-23T18:55:50.020Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 2 seconds","timestamp":"2023-08-23T18:55:50.021Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 1 seconds","timestamp":"2023-08-23T18:55:52.063Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 11 seconds","timestamp":"2023-08-23T18:55:53.714Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T18:55:57.603Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 9 seconds","timestamp":"2023-08-23T19:08:14.736Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 17 seconds","timestamp":"2023-08-23T19:08:14.738Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 6 seconds","timestamp":"2023-08-23T19:08:20.955Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 7 seconds","timestamp":"2023-08-23T19:08:20.956Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 7 seconds","timestamp":"2023-08-23T19:08:27.245Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 33 seconds","timestamp":"2023-08-23T19:08:28.417Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T19:08:34.334Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 2 seconds","timestamp":"2023-08-23T19:08:35.950Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 13 seconds","timestamp":"2023-08-23T19:08:35.951Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 26 seconds","timestamp":"2023-08-23T19:08:38.008Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 4 seconds","timestamp":"2023-08-23T19:09:27.406Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 15 seconds","timestamp":"2023-08-23T19:09:27.407Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 4 seconds","timestamp":"2023-08-23T19:09:31.581Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 5 seconds","timestamp":"2023-08-23T19:09:33.170Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 13 seconds","timestamp":"2023-08-23T19:09:33.172Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 14 seconds","timestamp":"2023-08-23T19:09:38.513Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 29 seconds","timestamp":"2023-08-23T19:09:46.501Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T19:09:52.882Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 6 seconds","timestamp":"2023-08-23T19:10:53.586Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 13 seconds","timestamp":"2023-08-23T19:10:53.593Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 5 seconds","timestamp":"2023-08-23T19:10:59.368Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 17 seconds","timestamp":"2023-08-23T19:10:59.373Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 12 seconds","timestamp":"2023-08-23T19:11:04.812Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 19 seconds","timestamp":"2023-08-23T19:11:17.268Z"}
{"code":"28000","file":"auth.c","length":169,"level":"error","line":"545","message":"Unable to establish database connection no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption","name":"error","routine":"ClientAuthentication","severity":"FATAL","stack":"error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption\n    at Parser.parseErrorMessage (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","timestamp":"2023-08-23T19:11:17.418Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 4 seconds","timestamp":"2023-08-23T19:12:48.231Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 17 seconds","timestamp":"2023-08-23T19:12:48.238Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 9 seconds","timestamp":"2023-08-23T19:12:52.955Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 4 seconds","timestamp":"2023-08-23T19:12:53.909Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 14 seconds","timestamp":"2023-08-23T19:12:53.915Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 13 seconds","timestamp":"2023-08-23T19:12:58.938Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption. Reconnecting in 38 seconds","timestamp":"2023-08-23T19:13:08.554Z"}
{"code":"28000","file":"auth.c","length":169,"level":"error","line":"545","message":"Unable to establish database connection no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption","name":"error","routine":"ClientAuthentication","severity":"FATAL","stack":"error: no pg_hba.conf entry for host \"105.112.190.241\", user \"usercomment\", database \"usercomment\", no encryption\n    at Parser.parseErrorMessage (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/Users/nwaobiemeka/Applications/Codebase/Risevest-interview-question/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)","timestamp":"2023-08-23T19:13:13.113Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 5 seconds","timestamp":"2023-08-23T19:13:18.239Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 9 seconds","timestamp":"2023-08-23T19:13:18.240Z"}
{"level":"error","message":"[Attempt #1]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 3 seconds","timestamp":"2023-08-23T19:13:23.918Z"}
{"level":"error","message":"[Attempt #2]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 3 seconds","timestamp":"2023-08-23T19:13:23.919Z"}
{"level":"error","message":"[Attempt #3]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 27 seconds","timestamp":"2023-08-23T19:13:27.144Z"}
{"level":"error","message":"[Attempt #4]. Unable to connect to Database: Error: connect ECONNREFUSED 127.0.0.1:5432. Reconnecting in 35 seconds","timestamp":"2023-08-23T19:13:27.537Z"}
{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"level":"error","message":"Unable to establish database connection connect ECONNREFUSED 127.0.0.1:5432","port":5432,"stack":"Error: connect ECONNREFUSED 127.0.0.1:5432\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)","syscall":"connect","timestamp":"2023-08-23T19:13:54.458Z"}
